# Generated by Django 4.2.8 on 2024-01-25 16:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentification', '0004_client_contact_number_client_preferred_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('date_heure', models.DateTimeField(default=datetime.datetime.now)),
                ('avocat_choisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.avocat')),
            ],
        ),
    ]
