# Generated by Django 4.2.8 on 2024-01-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='avocat_choisi',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='date_heure',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='email',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='telephone',
        ),
    ]
