# Generated by Django 4.2.8 on 2024-01-25 20:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_client_contact_number_client_preferred_language'),
        ('rendezvous', '0002_remove_rendezvous_avocat_choisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='avocat_choisi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentification.avocat'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='date_heure',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='nom',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='prenom',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='telephone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
