# Generated by Django 4.2.8 on 2024-01-25 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_client_contact_number_client_preferred_language'),
        ('rendezvous', '0003_rendezvous_avocat_choisi_rendezvous_date_heure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='avocat_choisi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentification.avocat'),
        ),
    ]
