# Generated by Django 4.2.8 on 2024-01-25 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_client_contact_number_client_preferred_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rendezvous', '0004_alter_rendezvous_avocat_choisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='avocat_choisi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.avocat'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='prenom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
    ]
