# Generated by Django 4.2.8 on 2024-01-25 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rendezvous', '0005_rendezvous_user_alter_rendezvous_avocat_choisi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
