# Generated by Django 4.2.8 on 2024-01-25 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendezvous', '0006_alter_rendezvous_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='user',
        ),
    ]
