# Generated by Django 4.2.8 on 2024-01-25 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rendezvous', '0007_remove_rendezvous_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='date_heure',
            field=models.DateTimeField(),
        ),
    ]
