# Generated by Django 4.2.8 on 2024-01-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='avocat',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
