# Generated by Django 4.2.8 on 2024-01-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_admin_phone_number_avocat_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='avocat',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='avocat',
            name='coordinates',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='avocat',
            name='experiences',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='avocat',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
