# Generated by Django 4.2.8 on 2024-01-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_remove_admin_phone_number_remove_avocat_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
