# Generated by Django 4.2.8 on 2024-01-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_client_contact_number_client_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='avocat',
            name='nom',
            field=models.CharField(default='Valeur par défaut', max_length=100),
        ),
        migrations.AlterField(
            model_name='avocat',
            name='experiences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
