# Generated by Django 4.2.8 on 2024-01-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_avocat_nom_alter_avocat_experiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avocat',
            name='nom',
            field=models.CharField(default='Valeur par défaut', max_length=500),
        ),
    ]
