# Generated by Django 4.2.8 on 2024-01-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_alter_avocat_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='avocat',
            name='langue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
